services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8912:8501
    volumes:
      - .:/app
    environment:
      - SECRETS_FILE=/app/secrets.toml
    command: ["python", "-m", "streamlit", "run", "./alcopt/app/Home.py"]
    # command: ["sleep", "infinity"]
    restart: unless-stopped
    # depends_on:
    #   - dnsmasq

  nginx:
    image: nginx:latest
    container_name: nginx-streamlit
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

networks:
  local-network:
    driver: bridge