services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8912:8501
    volumes:
      - ./data:/data
    environment:
      - SECRETS_FILE=/app/secrets.toml
    command: ["python", "-m", "streamlit", "run", "./alcopt/app/Home.py", "--server.port=8501", "--server.fileWatcherType=none"]
    restart: unless-stopped
    networks:
      - thomashayama-net

  app-dev:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8913:8501
    volumes:
      - .:/app
      - ./data:/data
    environment:
      - SECRETS_FILE=/app/secrets.dev.toml
    # command: ["python", "-m", "streamlit", "run", "./alcopt/app/Home.py", "--server.port=8501", "--server.fileWatcherType=watchdog"]
    command: ["sleep", "infinity"]
    restart: unless-stopped
    networks:
      - thomashayama-net

networks:
  thomashayama-net:
    driver: bridge
    external: true