[connections.alcopt_db]
uri = "sqlite:////data/alcopt.db"

[oauth.google]
AUTHORIZE_URL = "https://accounts.google.com/o/oauth2/auth"
TOKEN_URL = "https://oauth2.googleapis.com/token"
REFRESH_TOKEN_URL = "https://oauth2.googleapis.com/token"
REVOKE_TOKEN_URL = "https://oauth2.googleapis.com/revoke"
CLIENT_ID = ""
CLIENT_SECRET = ""
REDIRECT_URI = "https://www.thomashayama.com/alcopt"
SCOPE = "openid email profile"

[security]
admin = ["thomashayama@gmail.com"]